const amqpConfig = {
  url                       : 'amqp://127.0.0.1',
  heartbeatIntervalInSeconds: 30,
  reconnectTimeInSeconds    : 5,
  exchangeName              : 'cachex',
};

const exchangeType           = 'fanout';
const exchangeOptions        = { durable: false };
const queueOptions           = { durable: false };
const queueNameAutoGenerated = ''; // it will not be durable
const bindToAllRoutes        = '';
const publishToAllQueues     = '';
const publishTimeout         = 5000;
const prefetchMessageCount   = 1;

const cacherConfig = {
  stdTTL     : 0,
  checkperiod: 600,
};

const OPS = {
  SET: 1,
  DEL: -1,
};

module.exports = {
  amqpConfig,
  amqpSettings: {
    exchangeType,
    exchangeOptions,
    queueOptions,
    queueNameAutoGenerated,
    bindToAllRoutes,
    publishToAllQueues,
    publishTimeout,
    prefetchMessageCount,
  },
  cacherConfig,
  OPS,
};
